language: java

jdk:
  - openjdk8
  - openjdk11
  - openjdk12

script:
  - "./gradlew check"
  - "./gradlew sonarqube -Dsonar.login=$SONAR_TOKEN -Dsonar.projectKey=opel -Dsonar.organization=allegro -Dsonar.host.url=https://sonarcloud.io"

after_success:
  - bash <(curl -s https://codecov.io/bash)